"""force detection of all 11 tracking tables

Revision ID: 2c8c11481bca
Revises: 
Create Date: 2026-05-26 03:45:30.578839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c8c11481bca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_relation_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('friends',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('requester_id', sa.String(length=255), nullable=False),
    sa.Column('addressee_id', sa.String(length=255), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['addressee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'addressee_id', name='_friend_pair_uc')
    )
    op.create_table('lists',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('related_medias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_api_id', sa.String(length=255), nullable=False),
    sa.Column('media_relation_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_relation_type_id'], ['media_relation_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('original_api_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('banner_url', sa.Text(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('related_media', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_type'], ['media_types.id'], ),
    sa.ForeignKeyConstraint(['related_media'], ['related_medias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_media_type'), ['media_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_title'), ['title'], unique=False)

    op.create_table('list_items',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('list_id', sa.String(length=255), nullable=False),
    sa.Column('media_id', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_id', 'media_id', name='_list_media_uc')
    )
    op.create_table('user_media',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('media_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('liked', sa.Boolean(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('consumed_at', sa.Date(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('review_created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'media_id', name='_user_media_uc')
    )
    with op.batch_alter_table('user_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_media_media_id'), ['media_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_media_user_id'), ['user_id'], unique=False)

    op.create_table('user_top_items',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('top_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('top_id', 'media_id', name='_top_media_uc'),
    sa.UniqueConstraint('top_id', 'position', name='_top_position_uc')
    )
    op.create_table('user_media_likes',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('user_media_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_media_id'], ['user_media.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'user_media_id', name='_user_like_uc')
    )
    with op.batch_alter_table('user_media_likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_media_likes_user_media_id'), ['user_media_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_media_likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_media_likes_user_media_id'))

    op.drop_table('user_media_likes')
    op.drop_table('user_top_items')
    with op.batch_alter_table('user_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_media_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_media_media_id'))

    op.drop_table('user_media')
    op.drop_table('list_items')
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_title'))
        batch_op.drop_index(batch_op.f('ix_media_media_type'))

    op.drop_table('media')
    op.drop_table('related_medias')
    op.drop_table('lists')
    op.drop_table('friends')
    op.drop_table('users')
    op.drop_table('media_types')
    op.drop_table('media_relation_type')
    # ### end Alembic commands ###
